# Generated by Django 5.2.1 on 2025-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('host', 'Host'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='user', max_length=20, verbose_name='Role'),
        ),
    ]
