# Generated by Django 5.2.1 on 2025-05-11 08:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Check-in date')),
                ('end_date', models.DateField(verbose_name='Check-out date')),
                ('guests', models.PositiveSmallIntegerField(verbose_name='Number of guests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cleaning fee')),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Service fee')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special requests')),
                ('booking_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Booking reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP/Postal Code')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per night')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cleaning fee')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service fee')),
                ('bedrooms', models.PositiveSmallIntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Bathrooms')),
                ('accommodates', models.PositiveSmallIntegerField(verbose_name='Accommodates')),
                ('property_type', models.CharField(max_length=50, verbose_name='Property type')),
                ('image_urls', models.JSONField(default=list, verbose_name='Image URLs')),
                ('amenities', models.JSONField(default=list, verbose_name='Amenities')),
                ('house_rules', models.TextField(blank=True, verbose_name='House rules')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Check-in time')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Check-out time')),
                ('minimum_nights', models.PositiveSmallIntegerField(default=1, verbose_name='Minimum nights')),
                ('maximum_nights', models.PositiveSmallIntegerField(default=30, verbose_name='Maximum nights')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
