# Generated by Django 5.2.1 on 2025-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Image URLs'),
        ),
    ]
