# Generated by Django 5.2.1 on 2025-05-26 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_image_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_booking_review',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', True)), fields=('listing', 'reviewer'), name='unique_listing_review_no_booking'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('listing', 'reviewer', 'booking'), name='unique_booking_review'),
        ),
    ]
