# Generated by Django 5.2.3 on 2025-06-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='verification_video',
            field=models.FileField(blank=True, help_text='Video proof of property compliance (max 250MB, for moderation only)', null=True, upload_to='verification_videos/', verbose_name='Verification Video'),
        ),
    ]
