# Generated by Django 5.2.3 on 2025-06-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_verification_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Is edited'),
        ),
    ]
