# Generated by Django 5.2.1 on 2025-05-27 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_review_unique_booking_review_and_more'),
        ('moderation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='pending', max_length=20, verbose_name='Status')),
                ('moderator_notes', models.TextField(blank=True, verbose_name='Moderator Notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('required_changes', models.TextField(blank=True, verbose_name='Required Changes')),
                ('has_valid_title', models.BooleanField(default=False, verbose_name='Has Valid Title')),
                ('has_valid_description', models.BooleanField(default=False, verbose_name='Has Valid Description')),
                ('has_valid_images', models.BooleanField(default=False, verbose_name='Has Valid Images')),
                ('has_valid_address', models.BooleanField(default=False, verbose_name='Has Valid Address')),
                ('has_appropriate_pricing', models.BooleanField(default=False, verbose_name='Has Appropriate Pricing')),
                ('follows_content_policy', models.BooleanField(default=False, verbose_name='Follows Content Policy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_record', to='listings.listing', verbose_name='Listing')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_listings', to=settings.AUTH_USER_MODEL, verbose_name='Moderator')),
            ],
            options={
                'verbose_name': 'Listing Approval',
                'verbose_name_plural': 'Listing Approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('report_resolved', 'Report Resolved'), ('report_rejected', 'Report Rejected'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('content_removed', 'Content Removed'), ('content_edited', 'Content Edited')], max_length=30, verbose_name='Action Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Moderator')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='moderation.report', verbose_name='Related Report')),
                ('target_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='listings.listing', verbose_name='Target Listing')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL, verbose_name='Target User')),
            ],
            options={
                'verbose_name': 'Moderation Log',
                'verbose_name_plural': 'Moderation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
