# Generated by Django 5.2.1 on 2025-05-27 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_review_unique_booking_review_and_more'),
        ('moderation', '0003_listingapproval_moderationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('billing', 'Billing Issue'), ('booking', 'Booking Problem'), ('host_behavior', 'Host Behavior'), ('guest_behavior', 'Guest Behavior'), ('property_issue', 'Property Issue'), ('platform_bug', 'Platform Bug'), ('safety_concern', 'Safety Concern'), ('other', 'Other')], max_length=20, verbose_name='Complaint Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=15, verbose_name='Status')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('moderator_response', models.TextField(blank=True, verbose_name='Moderator Response')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Moderator')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL, verbose_name='Complainant')),
                ('related_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='listings.listing', verbose_name='Related Listing')),
            ],
            options={
                'verbose_name': 'User Complaint',
                'verbose_name_plural': 'User Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
