# Generated by Django 5.2.1 on 2025-05-29 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingimage'),
        ('moderation', '0004_usercomplaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomplaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Жалоба пользователя', 'verbose_name_plural': 'Жалобы пользователей'},
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='assigned_moderator',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='moderator_response',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='related_listing',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='subject',
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='listings.booking'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='moderator_notes',
            field=models.TextField(blank=True, verbose_name='Заметки модератора'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='complaint_type',
            field=models.CharField(choices=[('booking_issue', 'Проблема с бронированием'), ('listing_issue', 'Проблема с объявлением'), ('host_behavior', 'Поведение хоста'), ('guest_behavior', 'Поведение гостя'), ('safety_concern', 'Вопросы безопасности'), ('false_listing', 'Ложная информация в объявлении'), ('discrimination', 'Дискриминация'), ('payment_issue', 'Проблемы с оплатой'), ('cleanliness', 'Чистота'), ('other', 'Другое')], default='booking_issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='description',
            field=models.TextField(verbose_name='Описание жалобы'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('investigating', 'Расследуется'), ('resolved', 'Решено'), ('dismissed', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
