# Generated by Django 5.2.3 on 2025-06-11 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_review_is_edited'),
        ('moderation', '0006_listingapproval_has_verification_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomplaint',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='moderator_notes',
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='assigned_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный модератор'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Альтернативный email для связи', max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый ответ'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Заметки для внутреннего использования', verbose_name='Внутренние заметки'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='moderator_response',
            field=models.TextField(blank=True, help_text='Ответ, который увидит пользователь', verbose_name='Ответ модератора'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='subject',
            field=models.CharField(default='Жалоба', max_length=200, verbose_name='Тема жалобы'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='listings.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_made', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='complaint_type',
            field=models.CharField(choices=[('booking_issue', 'Проблема с бронированием'), ('listing_issue', 'Проблема с объявлением'), ('host_behavior', 'Поведение хоста'), ('guest_behavior', 'Поведение гостя'), ('safety_concern', 'Вопросы безопасности'), ('false_listing', 'Ложная информация в объявлении'), ('discrimination', 'Дискриминация'), ('payment_issue', 'Проблемы с оплатой'), ('cleanliness', 'Чистота'), ('other', 'Другое')], default='booking_issue', max_length=20, verbose_name='Тип жалобы'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='listings.listing', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, на которого жалуются'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Решено'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В обработке'), ('investigating', 'Расследуется'), ('awaiting_response', 'Ожидает ответа'), ('resolved', 'Решено'), ('dismissed', 'Отклонено'), ('escalated', 'Эскалировано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
