# Generated by Django 5.2.3 on 2025-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_remove_usercomplaint_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='action_type',
            field=models.CharField(choices=[('report_resolved', 'Report Resolved'), ('report_rejected', 'Report Rejected'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('content_removed', 'Content Removed'), ('content_edited', 'Content Edited'), ('subscription_created', 'Subscription Created'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_canceled', 'Subscription Canceled'), ('subscription_expired', 'Subscription Expired'), ('complaint_handled', 'Complaint Handled')], max_length=30, verbose_name='Action Type'),
        ),
    ]
