# Generated by Django 5.2.3 on 2025-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_alter_moderationlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaint',
            name='evidence_video',
            field=models.FileField(blank=True, help_text='Загрузите видео в качестве доказательства (макс. 100МБ)', null=True, upload_to='complaint_videos/', verbose_name='Видео-доказательство'),
        ),
    ]
