# Generated by Django 5.2.3 on 2025-06-12 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Setting name')),
                ('value', models.TextField(verbose_name='Value')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Default Subscription Setting',
                'verbose_name_plural': 'Default Subscription Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='Plan type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duration in days')),
                ('ads_limit', models.PositiveIntegerField(help_text='Maximum number of active ads', verbose_name='Ads limit')),
                ('featured_ads_limit', models.PositiveIntegerField(default=0, verbose_name='Featured ads limit')),
                ('premium_features', models.JSONField(blank=True, default=list, verbose_name='Premium features')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is popular')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Auto renew')),
                ('payment_reference', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Payment reference')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_count', models.PositiveIntegerField(default=0, verbose_name='Active ads count')),
                ('featured_ads_count', models.PositiveIntegerField(default=0, verbose_name='Featured ads count')),
                ('total_ads_created', models.PositiveIntegerField(default=0, verbose_name='Total ads created')),
                ('last_ad_created', models.DateTimeField(blank=True, null=True, verbose_name='Last ad created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='subscriptions.usersubscription')),
            ],
            options={
                'verbose_name': 'Subscription Usage',
                'verbose_name_plural': 'Subscription Usage',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('renewed', 'Renewed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('limit_check', 'Limit Check'), ('payment', 'Payment')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_actions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='subscriptions.usersubscription')),
            ],
            options={
                'verbose_name': 'Subscription Log',
                'verbose_name_plural': 'Subscription Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
